/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CounselorsRouteImport } from './routes/counselors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as ProgramProgramIdRouteImport } from './routes/program.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorsRoute = CounselorsRouteImport.update({
  id: '/counselors',
  path: '/counselors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramProgramIdRoute = ProgramProgramIdRouteImport.update({
  id: '/program/$programId',
  path: '/program/$programId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counselors': typeof CounselorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/roadmap': typeof RoadmapRoute
  '/admin/review': typeof AdminReviewRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counselors': typeof CounselorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/roadmap': typeof RoadmapRoute
  '/admin/review': typeof AdminReviewRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counselors': typeof CounselorsRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/roadmap': typeof RoadmapRoute
  '/admin/review': typeof AdminReviewRoute
  '/program/$programId': typeof ProgramProgramIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counselors'
    | '/dashboard'
    | '/explore'
    | '/roadmap'
    | '/admin/review'
    | '/program/$programId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/counselors'
    | '/dashboard'
    | '/explore'
    | '/roadmap'
    | '/admin/review'
    | '/program/$programId'
  id:
    | '__root__'
    | '/'
    | '/counselors'
    | '/dashboard'
    | '/explore'
    | '/roadmap'
    | '/admin/review'
    | '/program/$programId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounselorsRoute: typeof CounselorsRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  RoadmapRoute: typeof RoadmapRoute
  AdminReviewRoute: typeof AdminReviewRoute
  ProgramProgramIdRoute: typeof ProgramProgramIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselors': {
      id: '/counselors'
      path: '/counselors'
      fullPath: '/counselors'
      preLoaderRoute: typeof CounselorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program/$programId': {
      id: '/program/$programId'
      path: '/program/$programId'
      fullPath: '/program/$programId'
      preLoaderRoute: typeof ProgramProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounselorsRoute: CounselorsRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  RoadmapRoute: RoadmapRoute,
  AdminReviewRoute: AdminReviewRoute,
  ProgramProgramIdRoute: ProgramProgramIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
