// AUTO-GENERATED by scripts/sync-sheet.ts - do not edit by hand.
// This file is overwritten every time the sync script runs.
// It is merged into src/data/programs.ts's `seeds` array — see that file.
//
// This is the committed placeholder: an empty list, so the repo (and CI,
// which never has your local sync output) works standalone. Run
// `npm run sync:sheet` locally to regenerate this with real data from your
// Google Sheet, then `git add`/commit it yourself once you're happy with
// what it pulled in — it's deliberately never auto-committed.

type SheetSeed = {
  id?: string;
  title: string;
  org: string;
  category: "STEM" | "Business" | "Medicine" | "Law & Civics" | "Leadership" | "Arts";
  grades: number[];
  summary: string;
  description: string;
  eligibility: string;
  deadline: string | null;
  confidence: "confirmed" | "estimated" | "unposted";
  cost: string;
  format: string;
  location: string;
  url: string;
};

export const sheetSeeds: SheetSeed[] = [];
